### PR TITLE
Package can be used out of the box

### PR DESCRIPTION
**Pull request by Bert-Proesmans**
Hi, i made some changes to your setup.py file and moved package relevant python files into seperate directories.
These changes resulted in

- Pip automatically downloading the required packages on install

- 'utility.py' is included into the site-package, next to 'nnresample.py', so related import errors won't occur anymore

Note: I took the liberty of removing the requirements.txt file, since package requirements are now defined in 'setup.py'

### CODE REVIEW

**Review by jthiem — COMMENTED** [review]
Hi, thank you for your contribution! As you can tell, I'm new at creating packages... so this fixup is greatly appreciated.  One question though before I merge it: why the clause "<=1.0.0" in the install_requires stanza of setup.py (line 13)?

**Comment by Bert-Proesmans** [comment]
I'm not a pro about the topic; it's related to [semantic versioning](https://semver.org/).
"X.Y.Z", where X is only changed when API changes are incompatible with the previous version. 
I ran the library with the latest version of SciPy, which is 1.0.0, and nothing broke so i included it in the versioning. Granted i did not run any of the tests so my approach wasn't scientific.
The upper bound is basically to avoid any issues in the future when the SciPy API might change. 
> To follow the rule exactly it should have been "<1.0.0" unless thorough tessting results in no issues.

**Comment by jthiem** [comment]
If I understand it correctly, it should be "<2.0.0" since it should be guaranteed that the API will not change in the 1.x.x series. If the API changes, the scipy developers need to bump it to 2.0.0 and nnresample might no longer work.

**Comment by Bert-Proesmans** [comment]
Correct. I pushed a new commit with this change.
I also ran the tests to absolutely make sure it would work and as suspected no failures occurred.

**Comment by jthiem** [comment]
Great, thanks!

**Comment by Bert-Proesmans** [comment]
I'm embarrassed to say this, but the out the box experience is still broken. I didn't think through that importing `nnresample.__version__` would chainload scipy. Scipy could be missing from the users' environment before/during install resulting in install failure.
So the version has to be retrieved in a different way and the nnresample package should NOT be imported by 'setup.py'.
My apologies for this oversight.

**Pull request merged**
